/**
 * Migration: Create export_records table
 * 
 * Tracks every file export generated by the export engine.
 * The file is saved to disk at `file_path`; this record lets us serve
 * downloads and display export history in the UI.
 */
exports.up = async function (knex) {
  await knex.schema.createTable("export_records", (t) => {
    t.increments("id").primary();
    t.integer("job_id").unsigned().nullable()
      .references("id").inTable("scrape_jobs").onDelete("SET NULL");
    t.integer("user_id").unsigned().notNullable()
      .references("id").inTable("users").onDelete("CASCADE");
    // Export format chosen by the user
    t.enum("format", ["XLSX", "CSV", "HTML", "TXT"]).notNullable();
    // Absolute path on disk where the exported file was saved
    t.string("file_path", 2048).notNullable();
    // Optional metadata about the exported file
    t.integer("file_size").nullable();      // bytes
    t.integer("row_count").nullable();      // number of data rows
    t.timestamp("created_at").defaultTo(knex.fn.now()).notNullable();

    t.index(["user_id"]);
    t.index(["job_id"]);
  });
};

exports.down = async function (knex) {
  await knex.schema.dropTableIfExists("export_records");
};
