<h2>AI Sales Assistant</h2>
<p style="font-size:12px;color:var(--color-muted);">Recommendations below are generated by a deterministic rule-based heuristic - see <code>application/libraries/Dso_sales_assistant.php</code> - and, when an LLM provider is configured at <a href="<?php echo base_url('dyafa/aiconfig'); ?>">AI Config</a>, refined by the configured model. If no provider is configured or a call fails, the heuristic's own text is used unchanged.</p>
<?php if ($this->session->flashdata('dso_success')): ?>
<div class="dso-alert success"><?php echo $this->session->flashdata('dso_success'); ?></div>
<?php endif; ?>
<?php if (!empty($is_hod)): ?>
<p>
    <a class="dso-btn" href="<?php echo base_url('dyafa/aiassistant/generate'); ?>" onclick="return confirm('Generate new recommendations now?');">Generate Now</a>
    &nbsp;<a class="dso-btn" href="<?php echo base_url('dyafa/aiconfig'); ?>">AI Config</a>
</p>
<?php endif; ?>
<table class="dso-table">
<tr><th>Account</th><th>Type</th><th>Suggested Action</th><th>Suggested Property</th><th>Est. Revenue</th><th>Priority</th><th>Reason</th><th>Status</th><th>Actions</th></tr>
<?php foreach ($recommendations as $r): ?>
<tr>
    <td><?php echo htmlspecialchars($r->account_name); ?></td>
    <td><?php echo $r->type; ?></td>
    <td><?php echo htmlspecialchars($r->suggested_action); ?></td>
    <td><?php echo $r->suggested_property_name ? htmlspecialchars($r->suggested_property_name) : '-'; ?></td>
    <td><?php echo number_format($r->estimated_revenue, 2); ?></td>
    <td><span class="dso-badge <?php echo $r->priority === 'High' ? 'danger' : ($r->priority === 'Medium' ? 'warning' : ''); ?>"><?php echo $r->priority; ?></span></td>
    <td><?php echo htmlspecialchars($r->reason); ?></td>
    <td><?php echo $r->status; ?></td>
    <td>
    <?php if ($r->status === 'New'): ?>
        <a href="<?php echo base_url('dyafa/aiassistant/action/' . $r->id); ?>">Mark Actioned</a>
        &nbsp;<a href="<?php echo base_url('dyafa/aiassistant/dismiss/' . $r->id); ?>">Dismiss</a>
    <?php endif; ?>
    </td>
</tr>
<?php endforeach; ?>
</table>
