<h2>AI Sales Assistant - Next Best Actions</h2>
<p style="font-size:12px;color:var(--color-muted);">Lists <code>dso_ai_recommendations</code> rows of type <code>NextBestAction</code>, generated by <code>Dso_sales_assistant::find_accounts_needing_next_action()</code> for accounts with no logged sales activity in 21+ days.</p>
<p><a href="<?php echo base_url('dyafa/aiassistant'); ?>">&larr; Back to AI Sales Assistant</a></p>

<?php if (empty($recommendations)): ?>
<div class="dso-alert">No next best actions generated yet.</div>
<?php else: ?>
<table class="dso-table">
<tr><th>Account</th><th>Suggested Action</th><th>Suggested Property</th><th>Est. Revenue</th><th>Priority</th><th>Reason</th><th>Status</th><th>Actions</th></tr>
<?php foreach ($recommendations as $r): ?>
<tr>
    <td><?php echo htmlspecialchars($r->account_name); ?></td>
    <td><?php echo htmlspecialchars($r->suggested_action); ?></td>
    <td><?php echo $r->suggested_property_name ? htmlspecialchars($r->suggested_property_name) : '-'; ?></td>
    <td><?php echo number_format($r->estimated_revenue, 2); ?></td>
    <td><span class="dso-badge <?php echo $r->priority === 'High' ? 'danger' : ($r->priority === 'Medium' ? 'warning' : ''); ?>"><?php echo $r->priority; ?></span></td>
    <td><?php echo htmlspecialchars($r->reason); ?></td>
    <td><?php echo $r->status; ?></td>
    <td>
    <?php if ($r->status === 'New'): ?>
        <a href="<?php echo base_url('dyafa/aiassistant/action/' . $r->id); ?>">Mark Actioned</a>
        &nbsp;<a href="<?php echo base_url('dyafa/aiassistant/dismiss/' . $r->id); ?>">Dismiss</a>
    <?php endif; ?>
    </td>
</tr>
<?php endforeach; ?>
</table>
<?php endif; ?>
