<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

/**
 * AiAssistant - displays recommendations generated by
 * Cron::dso_generate_ai_recommendations() / Dso_sales_assistant::
 * generate_all_recommendations() (see Dso_sales_assistant.php, a documented
 * rule-based heuristic, not real ML, optionally enhanced by a configured LLM
 * provider - see Dso_llm_client.php / dyafa/AiConfig.php). No manual
 * create/edit form; generation happens via cron or the HOD-only
 * "Generate Now" action below, mirroring the Notifications controller.
 */
class AiAssistant extends Dso_Controller
{
    public function __construct()
    {
        parent::__construct();
        $this->load->model('dyafa/Dso_ai_recommendations_model');
        $this->load->model('dyafa/Dso_accounts_model');
        $this->load->model('dyafa/Dso_properties_model');
        $this->load->config('dso_roles');
    }

    public function index()
    {
        $hod_roles = $this->config->item('dso_hod_roles');
        $is_hod = in_array($this->dso_role(), $hod_roles, true);
        if ($is_hod) {
            $recommendations = $this->Dso_ai_recommendations_model->get_all();
        } else {
            $recommendations = $this->Dso_ai_recommendations_model->get_for_user($this->dso_user_id());
        }

        $data['recommendations'] = $this->_attach_labels($recommendations);
        $data['is_hod'] = $is_hod;
        $this->load->view('dyafa/layout/header');
        $this->load->view('dyafa/ai_assistant/list', $data);
        $this->load->view('dyafa/layout/footer');
    }

    public function action($id)
    {
        $this->Dso_ai_recommendations_model->mark_status($id, 'Actioned');
        $this->session->set_flashdata('dso_success', 'Recommendation marked as actioned.');
        redirect('dyafa/aiassistant');
    }

    public function dismiss($id)
    {
        $this->Dso_ai_recommendations_model->mark_status($id, 'Dismissed');
        $this->session->set_flashdata('dso_success', 'Recommendation dismissed.');
        redirect('dyafa/aiassistant');
    }

    /**
     * Manual "Generate Now" action - HOD-only, runs the exact same
     * generation logic as the cron job (Dso_sales_assistant::
     * generate_all_recommendations()), including the optional LLM
     * enhancement pass if a default provider is configured in
     * dyafa/aiconfig.
     */
    public function generate()
    {
        $this->require_role($this->config->item('dso_hod_roles'));
        $this->load->library('dso_sales_assistant');
        $counts = $this->dso_sales_assistant->generate_all_recommendations();
        $this->session->set_flashdata('dso_success', 'Recommendations generated (inactive accounts: '
            . $counts['inactive_accounts'] . ', contract renewals: ' . $counts['contract_renewals']
            . ', predictions: ' . $counts['predictions'] . ', next best actions: ' . $counts['next_best_actions'] . ').');
        redirect('dyafa/aiassistant');
    }

    /**
     * AI Sales Assistant > Predictions. Filters dso_ai_recommendations by
     * type = 'Prediction', populated by Dso_sales_assistant::
     * find_churn_risk_accounts() - accounts overdue for their next stay per
     * their own historical booking cadence (2+ past reservations required;
     * shows an empty state until "Generate Now"/cron has run at least once).
     */
    public function predictions()
    {
        $hod_roles = $this->config->item('dso_hod_roles');
        $is_hod = in_array($this->dso_role(), $hod_roles, true);
        $recommendations = $this->Dso_ai_recommendations_model->get_by_type('Prediction');
        if (!$is_hod) {
            $recommendations = array_values(array_filter($recommendations, function ($r) {
                return (int) $r->assigned_to === $this->dso_user_id();
            }));
        }

        $data['recommendations'] = $this->_attach_labels($recommendations);
        $data['is_hod'] = $is_hod;
        $this->load->view('dyafa/layout/header');
        $this->load->view('dyafa/ai_assistant/predictions', $data);
        $this->load->view('dyafa/layout/footer');
    }

    /**
     * AI Sales Assistant > Next Best Actions. Same pattern as predictions(),
     * filtered to type = 'NextBestAction', populated by Dso_sales_assistant::
     * find_accounts_needing_next_action() - active accounts with no logged
     * sales activity in 21+ days (an activity-based signal, distinct from
     * the reservation-based InactiveAccount/Prediction detectors).
     */
    public function next_best_actions()
    {
        $hod_roles = $this->config->item('dso_hod_roles');
        $is_hod = in_array($this->dso_role(), $hod_roles, true);
        $recommendations = $this->Dso_ai_recommendations_model->get_by_type('NextBestAction');
        if (!$is_hod) {
            $recommendations = array_values(array_filter($recommendations, function ($r) {
                return (int) $r->assigned_to === $this->dso_user_id();
            }));
        }

        $data['recommendations'] = $this->_attach_labels($recommendations);
        $data['is_hod'] = $is_hod;
        $this->load->view('dyafa/layout/header');
        $this->load->view('dyafa/ai_assistant/next_best_actions', $data);
        $this->load->view('dyafa/layout/footer');
    }

    /**
     * AI Sales Assistant > Analytics. Simple aggregate dashboard: counts of
     * recommendations by type and by status. No charting library in this app.
     */
    public function analytics()
    {
        $data['by_type'] = $this->Dso_ai_recommendations_model->counts_by_type();
        $data['by_status'] = $this->Dso_ai_recommendations_model->counts_by_status();
        $this->load->view('dyafa/layout/header');
        $this->load->view('dyafa/ai_assistant/analytics', $data);
        $this->load->view('dyafa/layout/footer');
    }

    protected function _attach_labels($recommendations)
    {
        foreach ($recommendations as $r) {
            $account = $this->Dso_accounts_model->get($r->account_id);
            $r->account_name = $account ? $account->company_name : 'Unknown';
            if ($r->suggested_property_id) {
                $property = $this->Dso_properties_model->get($r->suggested_property_id);
                $r->suggested_property_name = $property ? $property->name : null;
            } else {
                $r->suggested_property_name = null;
            }
        }
        return $recommendations;
    }
}
